services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://host.docker.internal:9200
    ports:
      - 5601:5601
    extra_hosts:
      - host.docker.internal:host-gateway
