services:
  fluentd:
    container_name: fluentd
    build: .
    ports:
      - '24224:24224/tcp'
      - '24224:24224/udp'
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: ['CMD', 'nc', '-vz', '-w1', '127.0.0.1', '8888']
      interval: 10s
      timeout: 10s
      retries: 5
