services:
  web-api-gateway:
    container_name: web-api-gateway
    image: web-api-gateway:local
    ports:
      - '30002:30002'
    env_file:
      - ./.env
    environment:
      - LOG_FORMAT=json
    extra_hosts:
      - 'host.docker.internal=host-gateway'
    dns:
      - 1.1.1.1
    healthcheck:
      test: 'nc -vz -w1 0.0.0.0 30002 && sleep 2'
      start_period: 2s
      interval: 2s
      timeout: 30s
      retries: 15
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: host.docker.internal:24224
        tag: web-api-gateway
