#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\nLint ==================\n"
npx nx affected -t lint --fix
npx lint-staged --relative

echo "\Unit Test & Build ==================\n"
npx nx affected -t test,ncc,server

echo "\E2E Testing ==================\n"
npx nx affected -t e2e --parallel=false
